[phases.setup]
nixPkgs = ["curl", "php83", "php83Extensions.mongodb", "php83Packages.composer", "nodejs_22"]

[phases.install]
cmds = ["composer install", "npm install"]

[phases.build]
cmds = ["npm run build"]
